# Generates r_generated.h: content-derived shader cache keys for ref_gl and ref_nri.
#
# Run as:  cmake -DSOURCE_DIR=<source> -DASSETS_DIR=<assets/data0_21pure> -DOUT=<r_generated.h> -P gen_glsl_cache_key.cmake
#
# Replaces the hand-bumped GLSL_BITS_VERSION. Each key is a positive 31-bit value so it fits the
# existing %i / atoi / uint32_t comparisons in the cache readers.

function(_hash_files out)
	set(acc "")
	foreach(f IN LISTS ARGN)
		if(EXISTS "${f}")
			file(SHA256 "${f}" h)
			# hash the path relative to SOURCE_DIR's parent so the key is stable across checkouts
			file(RELATIVE_PATH rel "${SOURCE_DIR}/.." "${f}")
			string(APPEND acc "${rel}:${h}\n")
		else()
			string(APPEND acc "${f}:missing\n")
		endif()
	endforeach()
	string(SHA256 digest "${acc}")
	string(SUBSTRING "${digest}" 0 7 top)
	math(EXPR key "0x${top}" OUTPUT_FORMAT DECIMAL)
	# 7 hex digits = 28 bits, never zero (zero marks an unfinished cache write)
	math(EXPR key "${key} + 1")
	set(${out} "${key}" PARENT_SCOPE)
endfunction()

file(GLOB_RECURSE gl_glsl  LIST_DIRECTORIES false "${ASSETS_DIR}/glsl/*")
file(GLOB_RECURSE nri_glsl LIST_DIRECTORIES false "${ASSETS_DIR}/glsl_nri/*")
list(SORT gl_glsl)
list(SORT nri_glsl)

_hash_files(KEY_GL
	${gl_glsl}
	"${SOURCE_DIR}/ref_gl/r_program.c"
	"${SOURCE_DIR}/ref_gl/r_program.h")

_hash_files(KEY_NRI
	${nri_glsl}
	"${SOURCE_DIR}/ref_nri/r_program.c"
	"${SOURCE_DIR}/ref_nri/r_program.h"
	"${SOURCE_DIR}/extern/glslang/known_good.json")

set(content "// GENERATED by ref_base/gen_glsl_cache_key.cmake -- do not edit, do not commit.
// Content hashes of everything that alters generated shader output. Not included: runtime cvars
// (r_shaderOptimize) and the GL driver hash, which ref_gl keys separately at runtime.
#ifndef R_GENERATED_H
#define R_GENERATED_H

#define R_GLSL_CACHE_KEY_GL  ${KEY_GL}
#define R_GLSL_CACHE_KEY_NRI ${KEY_NRI}

#endif
")

set(existing "")
if(EXISTS "${OUT}")
	file(READ "${OUT}" existing)
endif()
if(NOT existing STREQUAL content)
	get_filename_component(dir "${OUT}" DIRECTORY)
	file(MAKE_DIRECTORY "${dir}")
	file(WRITE "${OUT}" "${content}")
endif()
