name: Build

on: [push, pull_request]

jobs:
  linux:
    strategy:
      matrix:
        config: [release, debug]
    uses: ./.github/workflows/linux-build.yml
    with:
      config: ${{ matrix.config }}
    secrets: inherit
    
  macos:
    strategy:
      matrix:
        config: [release, debug]
    uses: ./.github/workflows/macos-build.yml
    with:
      config: ${{ matrix.config }}
    secrets: inherit
    
  windows:
    strategy:
      matrix:
        config: [release, debug]
    uses: ./.github/workflows/windows-build.yml
    with:
      config: ${{ matrix.config }}
    secrets: inherit

  test-linux:
    needs: linux
    strategy:
      matrix:
        config: [Release, Debug]
    runs-on: ubuntu-24.04
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Linux-x86_64-${{ matrix.config }}
          path: drop

      - name: Extract artifact
        working-directory: ./drop
        run: tar -xzf Linux-x86_64-${{ matrix.config }}.tar.gz

      - name: Unit Test
        working-directory: ./drop
        shell: bash
        run: |
          set -e
          for exc in ./test/*; do
            chmod +x $exc
            $exc
          done

  test-macos:
    needs: macos
    strategy:
      matrix:
        config: [Release, Debug]
    runs-on: macos-14
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: OSX-x86_64-${{ matrix.config }}
          path: drop

      - name: Extract artifact
        working-directory: ./drop
        run: tar -xzf OSX-x86_64-${{ matrix.config }}.tar.gz

      - name: Unit Test
        working-directory: ./drop/${{ matrix.config == 'Release' && 'Release' || 'Debug' }}
        shell: bash
        run: |
          set -e
          for exc in ./test/*[^.dSYM]; do
            chmod +x $exc
            $exc
          done

  test-windows:
    needs: windows
    strategy:
      matrix:
        config: [Release, Debug]
    runs-on: windows-2022
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: win-x86_64-${{ matrix.config }}
          path: drop

      - name: Extract artifact
        working-directory: .\drop
        run: 7z x win-x86_64-${{ matrix.config }}.zip -y

      - name: Unit Test
        shell: bash
        working-directory: .\drop
        run: |
          set -e
          for exc in ./test/*[^.pdb]; do
            chmod +x $exc
            $exc
          done
